MaisParana/MaisParana.Web/Controllers/GeralController.cs
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using Microsoft.PowerBI.Api.V2;
using Microsoft.PowerBI.Api.V2.Models;
using Microsoft.Rest;
using MaisParana.Web.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MaisParana.Web.Controllers
{
    public class GeralController : Controller
    {
        private static readonly string Username = ConfigurationManager.AppSettings["pbiUsername"];
        private static readonly string Password = ConfigurationManager.AppSettings["pbiPassword"];
        private static readonly string AuthorityUrl = ConfigurationManager.AppSettings["authorityUrl"];
        private static readonly string ResourceUrl = ConfigurationManager.AppSettings["resourceUrl"];
        private static readonly string ClientId = ConfigurationManager.AppSettings["clientId"];
        private static readonly string ApiUrl = ConfigurationManager.AppSettings["apiUrl"];
        private static readonly string GroupId = ConfigurationManager.AppSettings["groupId"];
        private static readonly string ReportId = ConfigurationManager.AppSettings["reportId"];

        public async Task<ActionResult> Index()
        {
            var result = new EmbedConfig();
            try
            {
                var error = GetWebConfigErrors();
                if (error != null)
                {
                    result.ErrorMessage = error;
                    return View(result);
                }

                //var platformParams = new PlatformParameters(context);

                // Create a user password cradentials.
                var credential = new UserPasswordCredential(Username, Password);

                // Authenticate using created credentials
                var authenticationContext = new AuthenticationContext(AuthorityUrl);
                var authenticationResult = await authenticationContext.AcquireTokenAsync(ResourceUrl, ClientId, credential);

                if (authenticationResult == null)
                {
                    result.ErrorMessage = "Authentication Failed.";
                    return View(result);
                }

                var tokenCredentials = new TokenCredentials(authenticationResult.AccessToken, "Bearer");

                // Create a Power BI Client object. It will be used to call Power BI APIs.
                using (var client = new PowerBIClient(new Uri(ApiUrl), tokenCredentials))
                {
                    // Get a list of reports.
                    var reports = await client.Reports.GetReportsInGroupAsync(GroupId);

                    Report report = reports.Value.FirstOrDefault(r => r.Name.Equals("geral"));

                    if (report == null)
                    {
                        result.ErrorMessage = "Group has no reports.";
                        return View(result);
                    }

                    var datasets = await client.Datasets.GetDatasetByIdInGroupAsync(GroupId, report.DatasetId);
                    result.IsEffectiveIdentityRequired = datasets.IsEffectiveIdentityRequired;
                    result.IsEffectiveIdentityRolesRequired = datasets.IsEffectiveIdentityRolesRequired;
                    GenerateTokenRequest generateTokenRequestParameters;

                    // Generate Embed Token for reports without effective identities.
                    generateTokenRequestParameters = new GenerateTokenRequest(accessLevel: "view");

                    var tokenResponse = await client.Reports.GenerateTokenInGroupAsync(GroupId, report.Id, generateTokenRequestParameters);

                    if (tokenResponse == null)
                    {
                        result.ErrorMessage = "Failed to generate embed token.";
                        return View(result);
                    }

                    // Generate Embed Configuration.
                    result.EmbedToken = tokenResponse;
                    result.EmbedUrl = report.EmbedUrl;
                    result.Id = report.Id;

                    return View(result);
                }
            }
            catch (HttpOperationException exc)
            {
                result.ErrorMessage = string.Format("Status: {0} ({1})\r\nResponse: {2}\r\nRequestId: {3}", exc.Response.StatusCode, (int)exc.Response.StatusCode, exc.Response.Content, exc.Response.Headers["RequestId"].FirstOrDefault());
            }
            catch (Exception exc)
            {
                result.ErrorMessage = exc.ToString();
            }

            return View(result);
        }

        /// <summary>
        /// Check if web.config embed parameters have valid values.
        /// </summary>
        /// <returns>Null if web.config parameters are valid, otherwise returns specific error string.</returns>
        private string GetWebConfigErrors()
        {
            // Client Id must have a value.
            if (string.IsNullOrEmpty(ClientId))
            {
                return "ClientId is empty. please register your application as Native app in https://dev.powerbi.com/apps and fill client Id in web.config.";
            }

            // Client Id must be a Guid object.
            Guid result;
            if (!Guid.TryParse(ClientId, out result))
            {
                return "ClientId must be a Guid object. please register your application as Native app in https://dev.powerbi.com/apps and fill client Id in web.config.";
            }

            // Group Id must have a value.
            if (string.IsNullOrEmpty(GroupId))
            {
                return "GroupId is empty. Please select a group you own and fill its Id in web.config";
            }

            // Group Id must be a Guid object.
            if (!Guid.TryParse(GroupId, out result))
            {
                return "GroupId must be a Guid object. Please select a group you own and fill its Id in web.config";
            }

            // Username must have a value.
            if (string.IsNullOrEmpty(Username))
            {
                return "Username is empty. Please fill Power BI username in web.config";
            }

            // Password must have a value.
            if (string.IsNullOrEmpty(Password))
            {
                return "Password is empty. Please fill password of Power BI username in web.config";
            }

            return null;
        }
    }
}

MaisParana/MaisParana.Web/Controllers/UserController.cs
using System.Web.Mvc;
using MaisParana.Web.DB;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using System.Net;
using Microsoft.Owin.Security;
using System.Web;
using MaisParana.Web.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Linq;

namespace MaisParana.Web.Controllers
{
    public class UserController : Controller
    {
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(User model)
        {
            return RedirectToAction("Index", "Dashboard");
        }
        
    }
}

MaisParana/MaisParana.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" sizes="96x96" href="../Content/assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Mais Paraná</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Bootstrap core CSS     -->
    <link href="../Content/assets/css/bootstrap.min.css" rel="stylesheet" />
    <!--  Paper Dashboard core CSS    -->
    <link href="../Content/assets/css/paper-dashboard.css" rel="stylesheet" />

    <!--  Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Raleway:800,600,400,300' rel='stylesheet' type='text/css'>
    <link href="../Content/assets/css/themify-icons.css" rel="stylesheet">

    <!-- Loading Jquery before to use on PowerBI -->
    <script src="../Content/assets/js/jquery-3.1.1.min.js" type="text/javascript"></script>
</head>
<body>
    <div class="wrapper">
        <div class="sidebar" data-background-color="brown" data-active-color="danger">
            <!--
                Tip 1: you can change the color of the sidebar's background using: data-background-color="white | brown"
                Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
            -->
            <div class="logo">
                <a href="http://www.maisparana.com.br">
                    <img src="~/Content/assets/img/logo-vertical-bck-b.png" style="width:180px">
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li>
                        <a href="@Url.Action("Index","Dashboard")">
                            <i class="ti-dashboard"></i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Geral")">
                            <i class="ti-support"></i>
                            <p>Geral</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Tuberculose")">
                            <i class="ti-map"></i>
                            <p>Tuberculose</p>
                        </a>
                    </li>
                    <li>
                        <a href="../Doc/Dicionario.pdf">
                            <i class="ti-book"></i>
                            <p>Dicionário</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Login","User")">
                            <i class="ti-share-alt"></i>
                            <p>Sair</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">

            @*<div class="content">
                <div class="container-fluid">
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>
            </div>*@

            @RenderBody()

            <footer class="footer">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="https://www.blueopen.org/">
                                    BlueOpen
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div class="copyright pull-right">
                        Mais Paraná
                        &copy;
                        <script>document.write(new Date().getFullYear())</script>, feito com <i class="fa fa-heart heart"></i> no <a href="http://bluehack.org/">Bluehack</a>.
                    </div>
                </div>
            </footer>
        </div>
    </div>
</body>

<!--   Core JS Files. Extra: TouchPunch for touch library inside jquery-ui.min.js   -->
<script src="../Content/assets/js/jquery-ui.min.js" type="text/javascript"></script>
<script src="../Content/assets/js/perfect-scrollbar.min.js" type="text/javascript"></script>
<script src="../Content/assets/js/bootstrap.min.js" type="text/javascript"></script>
<!--  Forms Validations Plugin -->
<script src="../Content/assets/js/jquery.validate.min.js"></script>
<!-- Promise Library for SweetAlert2 working on IE -->
<script src="../Content/assets/js/es6-promise-auto.min.js"></script>
<!--  Plugin for Date Time Picker and Full Calendar Plugin-->
<script src="../Content/assets/js/moment.min.js"></script>
<!--  Date Time Picker Plugin is included in this js file -->
<script src="../Content/assets/js/bootstrap-datetimepicker.js"></script>
<!--  Select Picker Plugin -->
<script src="../Content/assets/js/bootstrap-selectpicker.js"></script>
<!--  Switch and Tags Input Plugins -->
<script src="../Content/assets/js/bootstrap-switch-tags.js"></script>
<!-- Circle Percentage-chart -->
<script src="../Content/assets/js/jquery.easypiechart.min.js"></script>
<!--  Charts Plugin -->
<script src="../Content/assets/js/chartist.min.js"></script>
<!--  Notifications Plugin    -->
<script src="../Content/assets/js/bootstrap-notify.js"></script>
<!-- Sweet Alert 2 plugin -->
<script src="../Content/assets/js/sweetalert2.js"></script>
<!-- Vector Map plugin -->
<script src="../Content/assets/js/jquery-jvectormap.js"></script>
<!--  Google Maps Plugin   
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>  -->
<!-- Wizard Plugin    -->
<script src="../Content/assets/js/jquery.bootstrap.wizard.min.js"></script>
<!--  Bootstrap Table Plugin    -->
<script src="../Content/assets/js/bootstrap-table.js"></script>
<!--  Plugin for DataTables.net  -->
<script src="../Content/assets/js/jquery.datatables.js"></script>
<!--  Full Calendar Plugin    -->
<script src="../Content/assets/js/fullcalendar.min.js"></script>
<!-- Paper Dashboard PRO Core javascript and methods for Demo purpose -->
<script src="../Content/assets/js/paper-dashboard.js"></script>
<!-- Paper Dashboard PRO DEMO methods, don't include it in your project! -->
<script src="../Content/assets/js/demo.js"></script>

</html>